version: 2

jobs:
  build:
    docker:
      - image: golang:1.13
    working_directory: /go/src/github.com/whtcorpsinc/milevadb
    steps:
      - checkout
      - run:
          name: "Build & Test"
          command: make dev
