{
 "title": "Test-Cluster-MilevaDB-Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Server",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "graph",
     "description": "MilevaDB uptime since the last restart.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "(time() - process_start_time_seconds{job=\"milevadb\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Connection Count",
     "type": "graph",
     "description": "MilevaDB current connection counts.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "milevadb_server_connections", "legendFormat": "{{instance}}" },
      {
       "expr": "sum(milevadb_server_connections)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "MilevaDB CPU usage calculated with process CPU running seconds.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"milevadb\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "MilevaDB process rss memory usage.\nMilevaDB heap memory size in use.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"milevadb\"}",
       "legendFormat": "process-{{instance}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"milevadb\"}",
       "legendFormat": "HeapInuse-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Summary",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration",
     "type": "graph",
     "description": "MilevaDB query durations by histogram buckets with different percents.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_server_handle_query_duration_seconds_bucket{sql_type!=\"internal\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_server_handle_query_duration_seconds_bucket{sql_type!=\"internal\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "sum(rate(milevadb_server_handle_query_duration_seconds_sum{sql_type!=\"internal\"}[30s])) / sum(rate(milevadb_server_handle_query_duration_seconds_count{sql_type!=\"internal\"}[30s]))",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Failed Query OPS",
     "type": "graph",
     "description": "MilevaDB failed query statistics by query type.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(milevadb_server_execute_error_total[1m])) by (type, instance)",
       "legendFormat": " {{type}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Command Per Second",
     "type": "graph",
     "description": "MyALLEGROSQL command processing numbers per second. See https://dev.allegrosql.com/doc/internals/en/text-protocol.html and https://dev.allegrosql.com/doc/internals/en/prepared-memexs.html",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_server_query_total[1m])) by (result)",
       "legendFormat": "query {{result}}"
      }
     ]
    },
    {
     "title": "CPS By Instance",
     "type": "graph",
     "description": "MilevaDB query total statistics including both successful and failed ones.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_server_query_total[1m])) by (instance)",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "QPS",
     "type": "graph",
     "description": "MilevaDB memex statistics.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_interlock_memex_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(rate(milevadb_interlock_memex_total[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "CPS by CMD",
     "type": "graph",
     "description": "MyALLEGROSQL command statistics by command type. See https://dev.allegrosql.com/doc/internals/en/text-protocol.html and https://dev.allegrosql.com/doc/internals/en/prepared-memexs.html",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_server_query_total[1m])) by (type)",
       "legendFormat": " {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Detail",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Parse Duration",
     "type": "graph",
     "description": "The time cost of parsing ALLEGROALLEGROSQL to AST",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_stochastik_parse_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_stochastik_parse_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))",
       "legendFormat": "95"
      }
     ]
    },
    {
     "title": "Compile Duration",
     "type": "graph",
     "description": "The time cost of building the query plan",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_stochastik_compile_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_stochastik_compile_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))",
       "legendFormat": "95"
      }
     ]
    },
    {
     "title": "InterDircution Duration",
     "type": "graph",
     "description": "The time cost of executing the ALLEGROALLEGROSQL which does not include the time to get the results of the query .",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_stochastik_execute_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_stochastik_execute_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))",
       "legendFormat": "95"
      }
     ]
    },
    {
     "title": "Queries Using Causet Cache OPS",
     "type": "graph",
     "description": "MilevaDB plan cache hit total.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_server_plan_cache_total[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS",
     "type": "graph",
     "description": "MilevaDB transaction processing counts by type.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_stochastik_transaction_duration_seconds_count[1m])) by (type, txn_mode)",
       "legendFormat": "{{type}}-{{txn_mode}}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Bucketed histogram of transaction execution durations, including retry.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_stochastik_transaction_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le, txn_mode))",
       "legendFormat": "99-{{txn_mode}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(milevadb_stochastik_transaction_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le, txn_mode))",
       "legendFormat": "95-{{txn_mode}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(milevadb_stochastik_transaction_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le, txn_mode))",
       "legendFormat": "80-{{txn_mode}}"
      }
     ]
    },
    {
     "title": "Max Transaction Statement Num",
     "type": "graph",
     "description": "The max MilevaDB memexs numbers within one transaction.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(milevadb_stochastik_transaction_memex_num_bucket[30s])) by (le))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Max Transaction Retry Num",
     "type": "graph",
     "description": "The max MilevaDB transaction retry count.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum(rate(milevadb_stochastik_retry_num_bucket[30s])) by (le))",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Write Slow",
   "type": "event",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Request Duration 99 by causetstore",
     "type": "graph",
     "description": "KV request durations by causetstore (EinsteinDB). It contains requests that are executed automatically by the internal background.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_request_seconds_bucket{type!=\"GC\"}[1m])) by (le, causetstore))",
       "legendFormat": "causetstore-{{causetstore}}"
      }
     ]
    },
    {
     "title": "KV Request Duration 99 by type",
     "type": "graph",
     "description": "KV request durations by request type. It contains requests that are executed automatically by the internal background.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_einsteindbclient_request_seconds_bucket{type!=\"GC\"}[1m])) by (le,type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Request OPS",
     "type": "graph",
     "description": "KV request count by request type. It contains requests that are executed automatically by the internal background.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_request_seconds_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Transaction OPS",
     "type": "graph",
     "description": "MilevaDB total ekv transaction counts. It contains transactions that are executed automatically by the internal background.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_einsteindbclient_txn_cmd_duration_seconds_count[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Max Transaction Write Size Bytes",
     "type": "graph",
     "description": "The max writes bytes of the transaction. It contains transactions that are executed automatically by the internal background.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(milevadb_einsteindbclient_txn_write_size_bytes_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Max Transaction Write KV Num",
     "type": "graph",
     "description": "The max writes ekv count of the transaction. It contains transactions that are executed automatically by the internal background.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(milevadb_einsteindbclient_txn_write_kv_num_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Max Transaction Regions Num",
     "type": "graph",
     "description": "The max writes regions of the transaction. It contains transactions that are executed automatically by the internal background.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(milevadb_einsteindbclient_txn_regions_num_bucket[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FIDel TSO Wait Duration",
     "type": "graph",
     "description": "The duration of MilevaDB starts to wait for the TSO until received the TS result.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(FIDel_client_cmd_handle_cmds_duration_seconds_bucket{type=\"wait\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(FIDel_client_cmd_handle_cmds_duration_seconds_bucket{type=\"wait\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(FIDel_client_cmd_handle_cmds_duration_seconds_bucket{type=\"wait\"}[1m])) by (le))",
       "legendFormat": "90"
      }
     ]
    },
    {
     "title": "FIDel TSO RPC Duration",
     "type": "graph",
     "description": "The duration of a client starting to wait for the TS until received the TS result.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(FIDel_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(FIDel_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(FIDel_client_request_handle_requests_duration_seconds_bucket{type=\"tso\"}[1m])) by (le))",
       "legendFormat": "90"
      }
     ]
    },
    {
     "title": "AutoID QPS",
     "type": "graph",
     "description": "MilevaDB auto-ID requests per second including single causet/global auto-ID processing and single causet auto-ID rebase processing.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(milevadb_autoid_operation_duration_seconds_count[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "AutoID Duration",
     "type": "graph",
     "description": "MilevaDB auto-ID requests durations.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(milevadb_autoid_operation_duration_seconds_bucket[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "sum(rate(milevadb_autoid_operation_duration_seconds_sum[1m])) / sum(rate(milevadb_autoid_operation_duration_seconds_count[1m]))",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  }
 ]
}